# Generated by Django 4.1.2 on 2022-10-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='timestamp',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
